### PR TITLE
Add camera toggle button to enable/disable camera

### PR DESCRIPTION
**Pull request by wisechengyi**
PR for #14 

Other changes:
* memoized device window, so MainGUI does not have construct a new one every time.
* Proactively trigger `refreshDevicesIcon` on camera change events.

### CODE REVIEW

**Comment by apockill** [comment]
Hi Yi,

I have a couple things I would like you to address before I pull this into the main repository:
- Naming conventions: Please make sure that the new functions you add use camelCase, not snakeCase. I know that pep8 specifies snakecase, but since the entire project is camelCase it seems a bit out of place. Examples: get_toggle_button_text()
- I know that memoizing functions can be useful for optimization. But I don't think that a small utility function like this needs that, and since it involves adding a whole module to the project, I would rather avoid doing that. Could you change your implimentation so that it doesn't use util.py, or memoization? 

I think that's it. Other than that, it looks good!

**Comment by wisechengyi** [comment]
Addressed all comments. Should be good now. Thanks, Yi

**Comment by wisechengyi** [comment]
@apockill btw are you working in shenzhen now?

**Comment by wisechengyi** [comment]
ping

**Comment by apockill** [comment]
Hi Yi, sorry about the delay, it's been a busy few days. I'm actually studying in Arizona right now. 

Anyways, looks good! I'll pull it in.

**Comment by wisechengyi** [comment]
@apockill when you merge, you probably want to use the `squash` option on github. Otherwise a lot my meaningless commit messages will show up on master :P

**Pull request merged**
